chore: deps update
nextauthjs/docs pull request #142
Opened 2021-11-29 16:57 UTC by boredland

## Changes 💡

update all in-range updates so npm stops whining (a bit) and so the package-lock.json doesn't constantly diff.

2021-11-29 21:31 UTC, balazsorban44 requested changes
Please use npm@7 or newer. We are on the v2 version of the lockfile now.

2021-11-29 22:34 UTC, boredland commented on package.json
>      "remark-github": "^10.1.0",
a major release here would currently break because its only released as esm and docusaurus can't deal with that yet afaik...

2021-11-29 22:35 UTC, boredland commented on src/pages/index.js
> +    window
this is only to make eslint happy

2021-11-29 22:37 UTC, boredland commented on package.json
> -    "mermaid.cli": "^0.3.6",
the cli is not released separately anymore. and mermaid is a direct dep of "remark-mermaid-dataurl"

2021-11-29 22:38 UTC, boredland commented
> Please use npm@7 or newer. We are on the v2 version of the lockfile now.

done. and found some more.

2021-11-29 23:03 UTC, balazsorban44 requested changes
So much smaller lock file? I'm on mobile, but if that's  true, that's awesome! 🎉. 

I had a tiny request left only.

2021-11-29 23:03 UTC, balazsorban44 commented on package.json
> +    "lint:fix": "standard --fix && prettier --write scripts src versioned_docs versioned_sidebars *.js",
I don't think we need to run Prettier on old docs. just to avoid potentially humongous PRs in the future to old docs when we upgrade it.

2021-11-30 19:13 UTC, balazsorban44 approved these changes
Awesome, thank you!

2021-11-30 19:13 UTC, merged

2021-11-30 19:26 UTC, balazsorban44 commented
@boredland I think this PR unintentionally introduced too small bugs!:

![image](https://user-images.githubusercontent.com/18369201/144114117-a953f1bc-7ccb-483f-8a16-d777fd87cbc5.png)


The "markee" is gone behind the logo. I believe we had corporate logos swimming from right to left.

Also, the theme toggle shows a "not-allowed" cursor now. :thinking: Could you have a look and open a PR with a fix? :pray:

2021-11-30 19:28 UTC, balazsorban44 commented
Some info to use:

![image](https://user-images.githubusercontent.com/18369201/144114461-d96a71ee-4af3-4c78-bbf4-4dac992b91d7.png)


There is an extra class on the toggle.

Also, the marquee is there, just not showing up.

2021-11-30 20:13 UTC, boredland commented
Strange enough: the background with the moving logos is there for me:
![image](https://user-images.githubusercontent.com/4662748/144120438-e0e361d7-25b2-4466-b782-cde3504a89f4.png)
https://user-images.githubusercontent.com/4662748/144120800-33605f55-f2d8-4bec-bbc0-2b5330d3f7eb.mp4

aaaand I don't get the "toggleDisabled..." class on the toggle. Yes, I force refreshed. 😕

2021-11-30 22:39 UTC, balazsorban44 commented
It's gone for me as well... :eyes: huh, sorry, all good it seems... :sweat_smile: