Add new tutorial
nextauthjs/docs pull request #155
Opened 2021-12-03 16:00 UTC by gdangelo

Magic Link Authentication in Next.js with NextAuth and Fauna

## Changes 💡

I added a new tutorial for passwordless authentication with NextAuth + Fauna DB, with live example + code source.

## Affected issues 🎟

None.

## Screenshot (If Applicable) 📷

None.

2021-12-04 01:01 UTC, balazsorban44 commented on versioned_docs/version-v3/tutorials.md
> +- Configuring Next.js, NextAuth, and Fauna to work together seamlessly
```suggestion
- Configuring Next.js, NextAuth.js, and Fauna to work together seamlessly
```

2021-12-04 01:01 UTC, balazsorban44 commented on versioned_docs/version-v3/tutorials.md
> +- Using Fauna and the Fauna Adapter for next-auth to persist users, email sign in tokens, and sessions
```suggestion
- Using Fauna and the Fauna Adapter for `next-auth` to persist users, email sign in tokens, and sessions
```

2021-12-04 01:02 UTC, balazsorban44 requested changes
Hi, NextAuth.js v4 has recently been launched with quite a few changes, could you update your blog post?

https://next-auth.js.org/getting-started/upgrade-v4

2021-12-05 16:36 UTC, gdangelo commented
I just updated the tutorial with NextAuth.js v4 🔥

2021-12-05 16:44 UTC, balazsorban44 requested changes
Could you move this to https://github.com/nextauthjs/docs/blob/0fbb96a8835fab29f06034b13ee9e1966981795a/docs/tutorials.md

2021-12-05 17:12 UTC, gdangelo commented
Done! Sorry, I didn't realize I was still on the v3 docs ;)

2021-12-05 17:56 UTC, balazsorban44 approved these changes

2021-12-05 17:56 UTC, merged