Added how to use a custom base path in NextAuth
nextauthjs/docs pull request #203
Opened 2022-01-17 09:50 UTC by boutterudy

After being blocked myself for several days, I came across a discussion (#3635) referring to the basePath property of the SessionProvider. I think it's important to add these explanations because I couldn't find anything about it on the current documentation.

## Changes 💡
Added a section dedicated to the use of a custom base path in the documentation related to the configuration.

## Affected issues 🎟
Missing informations about usage of custom base path.

2022-01-17 11:56 UTC, balazsorban44 requested changes
Thank you! I think I would rather put this under https://next-auth.js.org/getting-started/client#options which is the place for the client configurations.

But otherwise looks good.

2022-04-17 14:57 UTC, boutterudy commented
Just to remind that I think that could be useful to add these sections to the documentation.

I'm waiting for a feedback 😉

2022-07-06 15:49 UTC, balazsorban44 approved these changes

2022-07-06 15:49 UTC, merged

2022-07-06 15:50 UTC, balazsorban44 commented
This should actually be opened on the monorepo instead https://github.com/nextauthjs/docs#note-we-have-migrated-the-docs-nextauthjsdocs-code-to-our-new-primary-monorepo-at-nextauthjsnext-auth-this-repository-will-be-deprecated-and-most-likely-archived-in-the-future